services:
  - type: web
    name: penjualan-senter-88
    runtime: php
    branch: main
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://penjualan-senter-88.onrender.com
